baseURL = "https://www.sammachin.com/"
languageCode = "en-us"
title = "Sam Machin"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true


[params]
title = "Sam Machin"
author = "Sam Machin"
description = "Product Manager, Hacker, Geek"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = ["css/custom.css"]
customJs = []
mainSections = []


## Social links
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/sammachin/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://twitter.com/sammachin"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/sammachin"

[[params.socialIcons]]
icon = "fab fa-youtube"
title = "YouTube"
url = "https://www.youtube.com/c/SamMachin"

[[params.socialIcons]]
icon = "fab fa-mastodon"
title = "Mastodon"
url = "https://chaos.social/@sammachin"
rel = "me"


## Menu items

[menu]

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
 
  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"
 
